apiVersion: v1
kind: ServiceAccount
metadata:
  name: go-sa
  namespace: gy
  annotations:
    # RRSA：把这里替换成你创建的 RAM Role ARN（形如 acs:ram::<uid>:role/<roleName>）
    alibabacloud.com/ram-role-arn: "acs:ram::1930344476137822:role/go-sa"

